### ISSUE TITLE
window font 및 ubuntu font 연동 issue

### ISSUE THREAD

**Issue by YuNie24** [parksunwoo/ocr_kor#11]
안녕하세요,

제공해주신 코드 흥미롭게 보았습니다.
데이터 생성을 실험하려고 보니 문제가 생겼습니다.

공유해주신 총 99개 폰트는 window 타입 같습니다.
Linux(Ubuntu 16.04) 환경에서 시도해보니 

computer_text_generator.py 파일의
image_font = ImageFont.truetype(font=bytes_font, size=font_size) 에서
아래 에러가 뜨네요,
`  File "/opt/conda/lib/python3.6/site-packages/PIL/ImageFont.py", line 173, in load_from_bytes
    "", size, index, encoding, self.font_bytes, layout_engine
OSError: unknown file format
"""
` 

font 에 우분투 기본 제공 폰트인 /usr/share/font 안의 ttf를 넣으니 에러는 나지 않습니다만 한글 적용이 안되는 폰트들이라 실험 진행이 안됩니다.

혹시 환경이 어떤 환경에서 진행하셨나요?

**Comment by parksunwoo** [comment]
안녕하세요 먼저 관심갖고 질문주셔서 감사드립니다.

우선 font는 공개되어있는 한글 ttf 파일로 진행했습니다. 
font 생성관련해서 참고했던 코드는 원래 영문기반이라 ttf 파일형식만 맞추면 되지않을까 싶습니다

제가 진행했던 환경은 우분투 환경이었습니다. 추가로 질문있으시면 남겨주세요

**Comment by sojjeong** [comment]
안녕하세요. 같은 문제를 접하고 나름대로 해결하여 댓글 남깁니다.

제가 확인 했을 때, font 폴더에 있는 폰트 중 TTE로 시작하는 폰트들이 깨져 있었습니다.
나눔글씨체를 남겨두고 TTE로 시작하는 폰트들을 지운 뒤 
generate_data_5type.sh 를 실행하면 제대로 작동하며 이미지가 생성되었습니다.

centos 환경에서 실행하였습니다.
잘못된 폰트 파일들을 삭제하고 실행해보셨으면 합니다.

**Comment by NeighborhoodCoding** [comment]
아 정말 감사합니다... TTE로 시작하는 폰트를 전부 지웠더니 OSError: unknown file format """문제가 저도 해결되었습니다.
