### ISSUE TITLE
env = lmdb.open(outputPath, map_size=1099511627776)

### ISSUE THREAD

**Issue by NeighborhoodCoding** [parksunwoo/ocr_kor#16]
제가 초보라서 질문을 많이해서 죄송합니다 ㅠㅠ

ocr_kor-master\data\create_lmdb_dataset.py에서

env = lmdb.open(outputPath, map_size=1099511627776)
줄에서 용량에러가 뜹니다.

제가 임의로 map_size를 줄이면 실행이 되긴 하는데 이것을 줄이면 어떠한 영향이 혹시 있는지 알 수 있을까요?
제가 너무 초보라서요 ㅠㅠ;;;

**Comment by SoongE** [comment]
질문자님의 컴퓨터가 200만원 이상이 아니라면 이 프로젝트는 SungmanHong님의 컴퓨터에서 실행시키기 힘들겁니다. Colab이라는 것을 검색해서 활용해보세요

**Comment by NeighborhoodCoding** [comment]
> 질문자님의 컴퓨터가 200만원 이상이 아니라면 이 프로젝트는 SungmanHong님의 컴퓨터에서 실행시키기 힘들겁니다. Colab이라는 것을 검색해서 활용해보세요

감사합니다^^ 제가 초보라서 대부분의 명령어가 리눅스기반으로 짜져있고 경로설정하기도 까다로울거 같은데 공부하면서 해봐야겠네요.....감사합니다..

**Comment by freedom9393** [comment]
Changing:
`env = lmdb.open(outputPath, map_size=1099511627776)`
to
`env = lmdb.open(outputPath, map_size=1073741824)`
worked for me

**Comment by phj799** [comment]
> 

Thank you so much!!
