### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by Doracoon** [parksunwoo/ocr_kor#17]
training 하는데 시간이 얼마나 걸리셨나요? google colab으로 돌려보려 하였으나 log_train.txt를 보니 0에서 끝난 모델도 있고, 300000다 진행한 모델도 보여서 저도 1에서 올라가질 않아서 질문드려봅니다.

**Comment by parksunwoo** [comment]
24가지 조합의  모델을 수행하는 것이라
Tesla P40 * 2 대와 1080 Ti * 4e 대로 3주정도 돌렸습니다.
