### ISSUE TITLE
evaluation data

### ISSUE THREAD

**Issue by hahalee98** [parksunwoo/ocr_kor#18]
좋은 자료 잘 보고 있습니다...
test를 돌리는데 평가 data가 없는데
evaluation data는 어디서 만드는건가요??

**Comment by hahalee98** [comment]
test.py를 열어보니 ['TRDG', 'AIHUB_WORD', 'AIHUB_CHAR']이라고 되어있는데 이 data들의 lmdb는 어디서 만드신건가요?

**Comment by parksunwoo** [comment]
안녕하세요

제가 연구를 진행했던 당시에는 AIHUB에서 char, word 단위 의 데이터셋만 제공했는데
현재는 문장단위 데이터셋까지 제공하고 있습니다. 이부분 참고해보시면 좋을듯합니다

AIHUB데이터가 아니라도 한글 이미지 데이터셋을 찾을수 있다면 아래 부분 참고하셔서
[create-lmdb-dataset](https://github.com/parksunwoo/ocr_kor#create-lmdb-dataset)

이미지에 대응되는 정답 텍스트 파일을 준비하시면 lmdb를 만드실 수 있습니다 감사합니다
