### ISSUE TITLE
 Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'

### ISSUE THREAD

**Issue by hahalee98** [parksunwoo/ocr_kor#19]
![image](https://user-images.githubusercontent.com/45969840/99185823-a3fcea80-278f-11eb-9508-d157efbb6a1a.png)

train을 하는데
다음과같은 오류가 발생합니다.

해결방법이 있을까요?

**Comment by parksunwoo** [comment]
GPU가 아닌 CPU 로 모델을 돌리시는 건가요?

에러 내용은 CPU로 GPU 코드를 수행하는 것이라 model.py 70 라인에서 에러 발생하는 중이네요.

**Comment by parksunwoo** [comment]
https://github.com/parksunwoo/ocr_kor/blob/master/deep-text-recognition-benchmark/modules/transformation.py#L152

해당 부분을 바꿔서 진행해보시면 정상 동작할 겁니다
