### ISSUE TITLE
안녕하십니까. 모델에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by wildbrother** [parksunwoo/ocr_kor#20]
한국어 단일 데이터셋에 대해 찾고 있던 와중에, 여기까지 흘러오게 되었습니다.
일단 글도 매우 잘 읽었고, 매우 유익하였습니다.

궁금한 점은 OCR 과 Scene text 태스크의 차이점이라면 , 
광학문자가 아닌 여러 글자체의 문자 또는 손글씨.. 그리고 실제 이미지에서 글자가 차지하는 영역의 정도 차이가 될 것이라고 생각합니다.

현재 이 Repo 에서 한국어를 다양한 글자체로 generate 하는 것으로 보이는데, 
이 경우 실제 도로사진이나 길거리 사진에서 문자를 recognition 하는 성능이 궁금합니다.

다양한 서체의 데이터셋이 실제이미지에서 다양한 글자체를 커버가능한지.. 해당 모델에서의 inference 이미지 같은 것을 공유해주실 수 있는지 질문드립니다. 
감사합니다.

**Comment by parksunwoo** [comment]
안녕하세요 관심갖고 문의주셔서 감사합니다

여기 repo 의 모델은 인쇄체 글씨체에만 집중해서 진행했습니다. 진행 당시에 한글 이미지 데이터를 구하기 어려워서요.
말씀하신 데이터셋은 아래 AIHUB 에 현재 구축되어있는 Text in the Wild 데이터셋과 같은 종류로 보입니다
[AIHUB-한국어 글자체 이미지](https://www.aihub.or.kr/aidata/133)

한번 해보시고 결과를 알려주셔도 좋을 것 같습니다 :)
감사합니다
