### ISSUE TITLE
안녕하세요. bert관련 질문 드립니다.

### ISSUE THREAD

**Issue by parkSJ-0172** [parksunwoo/ocr_kor#21]
안녕하세요. issue#6에서 kor-bert를 모델 조합에 추가하여 성능 개선 고려중이라고 말씀하셨는데, 혹시 정확히 어떤 방식으로 kor-bert를 활용하실 계획인지 궁금합니다.

**Comment by parksunwoo** [comment]
안녕하세요

bert를 추가해서 정확도를 높이려는 계획을 가지고 있었는데 아직 진행을 못하고 있었습니다
다시 진행해서 결과가 나온다면 업데이트 하겠습니다
혹시 그동안 진행해보셨다면 성능개선이 되었는지 알려주셔도 좋을 것 같습니다
