### ISSUE TITLE
범용적인 OCR이 아닌, 특정 내용만 잘 인식하면 될 경우 ko.txt 구성 문의 드립니다.

### ISSUE THREAD

**Issue by heloisekim** [parksunwoo/ocr_kor#22]
안녕하세요. 영문으로 작성된 원본 README를 국문으로 천천히 따라갈 수 있도록 잘 정리해주셔서 너무 감사합니다.
덕분에 synthetic data를 생성하는 데 큰 문제 없이 잘 진행할 수 있었습니다.
진행을 하다 보니, 몇 가지 호기심(?)이 생겨서 질문 드립니다.

저는 모든 종류의 인쇄물을 잘 인식하는 것이 목적이 아닌, 
특정 인쇄물을 입력받을 때 더 정확하게 글자가 인식되기를 원합니다.
예를 들어, 통장 사본, 고지서 등 '금액 항목'과 '금액'으로 주로 이루어진 인쇄물들입니다.

1. 이런 경우에는 ko.txt를 국립국어원 한국어 학습용 어휘목록이 아닌, 
    해당 인쇄물에서 주료 사용되는 단어들로만 구성해서 학습시켜도 좋은 결과를 얻을 수 있을지 궁금합니다. 
    (이름, 계좌번호, 주소, 금액 등)
2. 또한, ko.txt에 영어나 숫자를 포함시켜서 학습시켜도 문제가 없을지, 조언해주시면 감사하겠습니다. 
   (인쇄물이 국문+영문+숫자로 구성된 경우)

좋은 하루 되시기를 바랍니다. 감사합니다.

**Comment by parksunwoo** [comment]
안녕하세요

말씀하신대로 제가 진행한 경우에는 
일반적인 모든 경우를 고려해 한국어 학습용 어휘목록을 사용했습니다
1번 경우에는 해당하는 필요한 어휘들로만 학습을 시키는게 효율적이지 않을까싶습니다. 

2번 경우에는 영어나 숫자를 포함시켜 진행하셔도 될 것같습니다
train.py 에서 chracter 부분 파라미터를 변경해서 진행하셔야 합니다

감사합니다
