### ISSUE TITLE
한글 단어 모음집을 통해 데이터를 생성하였는데, 모음집에 없는 단어 ( ex. 조사, ~의, ~에, ~을, ~를) 처리는 어떻게 하셨나요?

### ISSUE THREAD

**Issue by hongym7** [parksunwoo/ocr_kor#23]
한글 단어 모음집을 통해 데이터를 생성하였는데, 모음집에 없는 단어 ( ex. 조사, ~의, ~에, ~을, ~를) 처리는 어떻게 하셨나요?

**Comment by parksunwoo** [comment]
예시의 이미지들을 보시면 여러단어의 조합이라 일반적인 문장과 달리 조사가 없습니다
실제 문장 데이터셋을 구하거나 다시 만들게 되면 조사를 포함해서 진행해볼 수 있을 것 같습니다
