### ISSUE TITLE
혹시 데이터 생성 시, 여러 단어를 한꺼번에 생성한 이유가 있을까요?

### ISSUE THREAD

**Issue by hongym7** [parksunwoo/ocr_kor#24]
혹시 데이터 생성 시, 여러 단어를 한꺼번에 생성한 이유가 있을까요?

예를 들어
'바나나' 1개의 단어만 사용하여 이미지를 생성한 것이 아니고
'바나나 사과 딸기' 와 같이 2개 이상의 단어를 사용하여 이미지를 생성

학습속도를 빠르게 하기 위함인지?
아니면 저런식으로 실제 문장은 여러 개의 단어로 구성되어 있기 때문인지?

추가적으로 띄어쓰기로 띄어져 생성된 단어는 '바나나' '사과' '딸기' 로 띄어져서 학습되는지요?

감사합니다.

**Comment by moduaiffel** [comment]
안녕하세요

말씀하신대로 실제 문장은 여러 개의 단어로 구성되어 있기때문에 여러단어를 조합해 문장길이를 맞춘것이구요
따라서 단어단위로 학습되지않고 문장단위로 학습되어집니다.

**Comment by parksunwoo** [comment]
안녕하세요 

말씀하신대로 실제 문장은 여러 개의 단어로 구성되어 있기 때문에 여러 단어를 조합해 문장단위로 만든 것이구요
단어단위가 아니라 문장단위로 학습되어집니다
