### ISSUE TITLE
opt 파일도 제공해주실 수 있으신가요?

### ISSUE THREAD

**Issue by kimlia545** [parksunwoo/ocr_kor#28]
ocr_kor 폴더에서
train.py  :  imgH 32 imgW 100 batch_max_length 25 (기본 네이버와 파라미터가 똑같습니다)
demo.py  :  imgH 32 imgW 400 max_batch_length 50으로 값이 서로 다릅니다
5개의 단어가 있는 학습이미지를 학습시키려고 하는데  max_batch_length 25면 
Filtering the images whose label is longer than opt.batch_max_length
ValueError: num_samples should be a positive integer value, but got num_samples=0
에러가 발생합니다

opt 파일 제공해주실 수 있으신가요?
감사합니다!

**Comment by parksunwoo** [comment]
5개의 단어가 있는 학습이미지를 학습시키려하시면 train.py 부터 
imgH, imgW를 알맞게 조정하셔서 진행하셔야 할 것 같습니다.

opt 파일은 아래 링크를 참고하시면 됩니다
https://github.com/parksunwoo/ocr_kor/blob/master/exprement2/TPS-VGG-BiLSTM-Attn-Seed9998/opt.txt
