### ISSUE TITLE
Number of training data

### ISSUE THREAD

**Issue by qutrino** [parksunwoo/ocr_kor#8]
안녕하세요. 좋은 내용 공유해주셔서 너무 감사합니다. 
논문과 코드를 보다보니 훈련데이터 관련 궁금한 점이 생겨서 문의드려요.

basic 데이터 기준으로, 
generate_data_5type.sh 에는 9000번 run.py를 돌게 되어있고, 
run.py에서 또다시  1000문장을 만드는것 같은데..
그럼 9백만개의 문장을 만들게 되는건지 궁금합니다.

**Comment by parksunwoo** [comment]
안녕하세요 제가 진행하는 프로젝트에 관심가져주셔서 감사합니다
우선 TextRecognitionDataGenerator 프로젝트의 기본명령어는 아래와 같은 형태인데 
한글 폰트에 대해서는 명령어가 제대로 수행되지 않았습니다.

python run.py **-c 9000** -w 10 -f 64 -l ko --output_dir out/basic;

그래서 제가 임의의 방법으로 for 문을 수행해서 데이터를 생성한 것이구요. 
위 명령어로 먼저 수행해보시고, generate_data_5type.sh 도 참고하시면 될 것 같습니다

**Comment by qutrino** [comment]
답변감사드립니다. 적어주신대로 run.py 직접돌려서 시도해봤는데, 잘 되는듯 합니다.
